vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    trick_thumbnail:
      uri_prefix: /uploads/tricks
      upload_destination: '%kernel.project_dir%/public/uploads/tricks'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer