version: '3'

services:
  database:
    image: mysql
    container_name: database_snowtricks
    restart: always
    volumes:
      - database-data:/laragon/bin/data/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmni_snowtricks
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
    networks:
      - dev

  www:
    build: docker
    container_name: www_snowtricks
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/laragon/www
    networks:
      - dev

networks:
  dev:

volumes:
  database-data:

